# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
builds:
  - binary: authserver
    main: ./cmd/main.go
    flags:
      - -v
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
source:
    enabled: true
    name_template: "{{ .ProjectName }}"
    format: "tar.gz"
changelog:
  skip: true
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: markliederbach
    name: auth-server
  draft: true
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"