name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Install Taskfile
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          sudo mv ./bin/task /usr/local/bin
      - name: Install GoReleaser
        run: |
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
          sudo mv ./bin/goreleaser /usr/local/bin
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Run build
        run: task build
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: authserver
          path: dist/tflint-validate-tags*.zip